### ISSUE TITLE
Input  or MD_files folder

### ISSUE THREAD

**Issue by HubLot** [NMRLipids/nmrlipids.blogspot.fi#22]
Regarding issue #17, this folder could contain all starting files to re-launch the MD simulations easily. It could be divided by forcefield and sub-divided by the type of the lipid and the condition.
Zenodo link in README to indicate where to retrieve the trajectory files.
I'll make a PR in this way so you can have a better view (#23)

Here a list of all simulations which could be include in this folder (taken from both manuscripts):
- [x] ~~Charmm36 POPC/72~~ (#23)
- [x] ~~Charmm36 POPC/128~~ (#46)
- [x] ~~Charmm36 POPC Cholesterol (by me)~~  (#23)
- [x] ~~Charmm36 POPC Cholesterol (by Favela)~~ (no input files)
- [x] ~~Charmm36 POPC/72 NaCl set (13, 26, 52, 78 number)~~ (#23)
- [x] ~~Charmm36 POPC/72 Dehydration set (15 and 7 w/l)~~ (#23)
- [x] ~~Charmm36 DPPC/72~~ (no input files)
- [x] ~~Berger-POPC-07 POPC/128~~ (#24)
- [x] ~~Berger-POPC-07 POPC/128 Dehydration (7w/l)~~ (#24)
- [x] ~~Berger-POPC-07 POPC/128 Cholesterol (6, 14, 34, 50, 61 %)~~ (#24)
- [x] ~~Berger-POPC-07 POPC/128 NaCl~~ (44) (#24)
- [x] ~~Berger-POPC-07 POPC/128 CaCl2 (44/88)~~ (not used in this manuscript)
- [x] ~~Berger-DPPC-98 DPPC/72~~ (#24)
- [x] ~~Berger-DMPC-04 DMPC/128~~ (no input files)
- [x] ~~MacRog POPC/288~~ (#24)
- [x] ~~MacRog POPC/288 Dehydration (25, 20, 15, 10, 5 w/l)~~ (#24)
- [x] ~~MacRog POPC/288 Cholesterol (11, 44, 50, 56 %)~~ (#24)
- [x] ~~MacRog POPC/288 NaCl (27, 54, 81, 108)~~ (#24)
- [x] ~~GAFFlipid POPC/126~~ (#25)
- [x] ~~GAFFlipid POPC/126 Dehydration (7 w/l)~~ (#25)
- [x] ~~GAFFlipid DPPC/72~~ (#25)
- [x] ~~Lipid14 POPC/72~~ (#28)
- [x] ~~Poger DPPC/128~~ (#28)
- [x] ~~Slipids DPPC/128~~ (#28)
- [x] ~~Slipids DPPC/128 NaCl (49)~~ (not used in this manuscript)
- [x] ~~Slipids POPC/128~~ (#28)
- [x] ~~Kukol POPC/512~~ (#28)
- [x] ~~Chiu POPC/128~~ (#28)
- [x] ~~Högberg08 POPC/128~~ (#28)
- [x] ~~Högberg08 DMPC/98~~ (#28)
- [x] ~~Ulmschneiders POPC/128~~ (#29)
- [x] ~~Tjörnhammar14 DPPC/144~~ (#29)
- [x] ~~Charmm36-UA DPPC/72~~ (#46)
- [x] ~~CharmmXX-UA DLPC/128~~ (#46)
- [x] ~~Orange POPC NaCl (7, 26, 50)~~ (not used in this manuscript)
- [x] ~~Orange POPC CaCl2 (26/52)~~ (not used in this manuscript)

**Comment by HubLot** [comment]
Edit the 1st comment to add the list of MD simulations

**Comment by HubLot** [comment]
with the last PR (#46), almost all input files for the simulations described in the manuscript is added.
3 sets of simulations are missing due to the lack of input files, only the trajectory files are stored:
- Charmm36 POPC Cholesterol (by Favela)
- Berger-DMPC-04 DMPC/128
- Charmm36 DPPC/72

The others simulations (with ions) are not used in this manuscript so it's not needed to add them here.

Once the pull-request is merge, I think the issue can be closed. Hihaa!
